// generated by Fast Light User Interface Designer (fluid) version 1.0200

#ifndef HelloWorld_h
#define HelloWorld_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>

class HelloWorld {
public:
  Fl_Double_Window* make_window();
};
#endif
